# Generated by Django 3.2.8 on 2021-10-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211010_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='customer',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
